### ISSUE TITLE
Truncate overflowing cell contents using an ellipsis

### ISSUE THREAD

**Issue by stevenvachon** [gajus/table#1]
Make it an option to truncate cell contents using an ellipsis instead of auto-wrap.

**Comment by gajus** [comment]
I don't think this belongs as an option. User is able to truncate contents before passing it to the table, e.g. 

```js
let data,
    output,
    options;

data = [
    ['0A', '0B', '0C'],
    ['1A', '1B', '1C'],
    ['2A', '2B', '2C']
];

data = _.map((row) => {
    // Truncate the second column to 30 characters.
    row[1] = _.trunc(row[1], 30, '...');

    return row;
});

output = table(data);

console.log(output);
```

The only problem with this approach is that it will not work when a string that contains fullwidth characters or ANSI escape codes. I will write a package to do that.

**Comment by gajus** [comment]
Added. https://github.com/gajus/table/commit/648cd43576fba6d20b62b838e318c2375be29ede

**Comment by mk-pmb** [comment]
Thanks for this impressive package!
How do I configure which character(s) are used as the ellipsis mark?

**Comment by gajus** [comment]
This feature is not implemented at the moment. Though it would be a simple change. PR is welcome.

**Comment by mk-pmb** [comment]
Wow, you're quick! Ok, PR pending.

**Comment by mk-pmb** [comment]
My idea for an implementation would require table to define its own default for omission. Lodash is [undecided](https://github.com/lodash/lodash/issues/2562) about whether to use `…` or `...`; should I await their decision and use that, keep the effective old behavior, or take a bold step towards modern fonts? ;-)

**Comment by mk-pmb** [comment]
I got stuck at "Error: Invalid config", so for now I can only supply [this preview](https://github.com/mk-pmb/table-node/commit/9f1570cb54e5849f59b3c68ee9956770a7d2014c) with an old ES5 style function that I copy-pasted in order to manually test it. I hope someone more familiar with your build system and docs generator can plug that more nicely, add real tests and a more motivated mention in the readme.
