### ISSUE TITLE
Rendering text tables in emails?

### ISSUE THREAD

**Issue by tommedema** [gajus/table#106]
Output tables render fine in a terminal, but whitespace does not seem aligned in emails.

E.g. in terminal:

![Screen Shot 2019-10-07 at 6 05 53 PM](https://user-images.githubusercontent.com/331833/66359744-21b7bb00-e92d-11e9-8b7a-6b59b5954945.png)

In gmail:

![Screen Shot 2019-10-07 at 6 06 15 PM](https://user-images.githubusercontent.com/331833/66359761-31cf9a80-e92d-11e9-98f5-5b29ea7899f5.png)

Even when replacing whitespace to literal html characters like:

```javascript
      output
      .replace(/\n/g, '<br>')
      .replace(/ /g, '&nbsp;')
```

Has anyone worked around this issue? Any advice would be greatly appreciated

**Comment by nam-hle** [comment]
There is no way to do that. The package is intended to work on the terminal environment only.
