### ISSUE TITLE
How can I create a header row that's bold?

### ISSUE THREAD

**Issue by RobertSmith8** [gajus/table#108]
Chalk works great in terminal but is not useful for a Discord bot. I tried to use:

`data = [         
        ['**User**', '**Level**']
 ];`

But result was `**User**` instead of  **User**

Is there any alternative to chalk if I want a header row that's bold?

**Comment by marklagendijk** [comment]
You can use `chalk.bold` for this. Example:

``` javascript
const { table } = require('table');
const chalk  = require('chalk');

module.exports = {
    printTable
};

function printTable(data, properties) {
    const header = properties.map(property => chalk.bold(property));
    const tableText = table([
        header,
        ...data.map(item => properties.map(property => item[property]))
    ]);
    console.log(tableText);
}

```
