### ISSUE TITLE
drawVerticalLine

### ISSUE THREAD

**Issue by quoininc-huudatran** [gajus/table#110]
Can we get a `drawVertialLine(index, size)` just like `drawHorizontalLine(index, size)` so that it's easy to create a matrix-like:

```
+---+-----------+
|   | A   B   C |
+---+-----------+
| A | -   1   2 |
| B | 1   -   2 |
| C | 2   2   - |
+---+-----------+
```

**Comment by nam-hle** [comment]
This issue can be closed.
