### ISSUE TITLE
Character loss due to encoding

### ISSUE THREAD

**Issue by hmmhmmhm** [gajus/table#112]
![스크린샷 2020-05-19 오후 4 39 04](https://user-images.githubusercontent.com/38493722/82298652-62ad9d00-99ef-11ea-9b20-016c4da22e83.png)

![스크린샷 2020-05-19 오후 4 39 13](https://user-images.githubusercontent.com/38493722/82298676-6c370500-99ef-11ea-974a-2410120da579.png)

If a character such as Hangeul goes through this library, some of the characters will be lost.
Perhaps an error is caused by letters exceeding 2 byte.

**Comment by hmmhmmhm** [comment]
![스크린샷 2020-05-19 오후 4 47 02](https://user-images.githubusercontent.com/38493722/82299380-67bf1c00-99f0-11ea-9110-64b3fdcc7dc5.png)

I think this is an error caused by this module using string-width module.
Pure Javascript can calculate the exact number of characters in Unicode characters.
(`가`.length is always 1)

However, the string-width module appears to calculate the number of bytes, not letters.

**Comment by gajus** [comment]
Happy to replace `string-width` if there is a better alternative.

**Comment by hmmhmmhm** [comment]
I don't know why you're trying to use that module, is there an example that you can't handle with pure JavaScript length?
