### ISSUE TITLE
wrapWord is broken

### ISSUE THREAD

**Issue by stavalfi** [gajus/table#131]
I may not use this feature correctly but I don't want to set every column-width to some constant value.

```javascript
console.log(
  table(
    [
      [
        'afjiewnfwe f erfg rhe fgher fgbj ergbjler jblgn erbjg jlerb wnfwe f erfg rhe fgher fgbj ergbjler jblgn erbjg jlerb wnfwe f erfg rhe fgher fgbj ergbjler jblgn erbjg jlerb greh gerbjn gbre gjlerjlg bjrne gljre gejnb rljnr ljner grbjnle gerlj',
        'afjiewnfwe f erfg rhe fgher fgbj ergbjler jblgn erbjg jlerb wnfwe f erfg rhe fgher fgbj ergbjler jblgn erbjg jlerb wnfwe f erfg rhe fgher fgbj ergbjler jblgn erbjg jlerb greh gerbjn gbre gjlerjlg bjrne gljre gejnb rljnr ljner grbjnle gerlj',
      ],
      [
        'afjiewnfwe f erfg rhe fgher fgbj ergbjler jblgn erbjg jlerb wnfwe f erfg rhe fgher fgbj ergbjler jblgn erbjg jlerb wnfwe f erfg rhe fgher fgbj ergbjler jblgn erbjg jlerb greh gerbjn gbre gjlerjlg bjrne gljre gejnb rljnr ljner grbjnle gerlj',
        'afjiewnfwe f erfg rhe fgher fgbj ergbjler jblgn erbjg jlerb wnfwe f erfg rhe fgher fgbj ergbjler jblgn erbjg jlerb wnfwe f erfg rhe fgher fgbj ergbjler jblgn erbjg jlerb greh gerbjn gbre gjlerjlg bjrne gljre gejnb rljnr ljner grbjnle gerlj',
      ],
    ],
    {
      columnDefault: {
        wrapWord: true,
      },
    },
  ),
)
```

![image](https://user-images.githubusercontent.com/12954665/103448596-72d76b80-4ca4-11eb-8b96-63c846b284ca.png)

---------

```
table@6.0.4
node v15.3.0
mac-os 10.14.1
terminal: iterm2 3.3.12
```

**Comment by gajus** [comment]
`wrapWord` just says "break text near word-break". You need to column `width`.

See this example:

https://github.com/gajus/table/blob/fb887329abcb2eb6e01cec4c1d5d9daa2b0effb6/test/README/usage/text_wrapping.js#L45-L46

**Comment by stavalfi** [comment]
@gajus thanks for the quick response.

I think you missed the hole point of this issue: I don't want to specify custom width.

I want a responsive table based on the terminal size.

**Comment by gajus** [comment]
That's not a feature. But, it sounds a reasonable ask.

We could add option `audoWrap`. PR would be accepted.

**Comment by stavalfi** [comment]
@gajus thanks.

can you reopen?

**Comment by gajus** [comment]
You are free to work on the issue. As it is not an issue I would actively work, I will keep it closed. That doesn't prevent anyone from contributing.
