### ISSUE TITLE
Regression: columns config cannot be an array

### ISSUE THREAD

**Issue by aomarks** [gajus/table#134]
Somewhere between versions `6.0.3` and `6.0.7`, passing an array of column configs stopped working. A validation error is now raised. The workaround is to pass an object with numeric keys. I think the array form is more natural and should also be valid.

**Input**:
```js
table(rows, {
  columns: [
    { alignment: 'right' }
  ]
});
```

**Error**:
```js
errors [
  {
    dataPath: '/columns',
    message: 'should be object',
    params: { type: 'object' },
    schemaPath: '#/type'
  }
]
```

**Workaround**:
```js
table(rows, {
  columns: {
    0: { alignment: 'right' }
  }
});
```

**Comment by nam-hle** [comment]
This issue is resolved. Please help me close it @gajus
