### ISSUE TITLE
Reduce disk footprint

### ISSUE THREAD

**Issue by TimvdLippe** [gajus/table#137]
As part of https://github.com/eslint/eslint/issues/14098 we are looking at all dependencies of ESLint and which ones are causing a larger than desirable disk footprint. `table` is one of the packages that depends on `lodash`, which is 4.8MB (https://github.com/eslint/eslint/issues/14098#issuecomment-782158309). At this point, one of the options the ESLint maintainers are looking at is removing the `table` formatter: https://github.com/eslint/eslint/issues/14098#issuecomment-790273307

Rather than removing the formatter, it would be ideal if the disk footprint of `table` could be reduced. Luckily, there appears to be a PR open to remove `lodash`, which should help considerably: #136 Could you audit your dependencies and look if there are any easy wins in terms of reducing the disk footprint of the NPM package? Thanks in advance!

**Comment by TimvdLippe** [comment]
@gajus Do you mind taking a look at #136? I think that would largely resolve this issue.

**Comment by jeremyVignelles** [comment]
We also might remove these dependencies: https://github.com/gajus/table/blob/master/package.json#L9-L11

Having read quickly through the code, they don't seem to be really useful. I'll try to open a PR in the next few days.

**Comment by jeremyVignelles** [comment]
#159
