### ISSUE TITLE
Chinese has been  cutted

### ISSUE THREAD

**Issue by vk-bytedance** [gajus/table#175]
**Problem 1: Chinese words has been cutted.**
here is my code:

`
const { table } = require('table');
`
`
const data = table([['哈哈哈哈', '呵呵呵呵']]);
`

resule is
![screenshot-20210511-182234](https://user-images.githubusercontent.com/80667117/117801077-726c6400-b286-11eb-8c56-9c8c0413eedc.png)

The data has four words each item, why it just show two words.

**Problem 2: The table style is not right.**
english version
![image](https://user-images.githubusercontent.com/80667117/117801116-8021e980-b286-11eb-806a-2ed7ba1972d8.png)
chinese version
chinese has been cutted and table style is not right
![image](https://user-images.githubusercontent.com/80667117/117801187-94fe7d00-b286-11eb-8dbe-12cc0ec70541.png)

**Comment by nam-hle** [comment]
@vk-bytedance Can you confirm the bug is fixed? 😍

**Comment by vk-bytedance** [comment]
> @vk-bytedance Can you confirm the bug is fixed? 😍

I can't install table@6.7.1.
The command 'npm view table' tell me that the latest version is 6.7.0.

**Comment by nam-hle** [comment]
How about `npm install table@6.7.1`

**Comment by vk-bytedance** [comment]
![image](https://user-images.githubusercontent.com/80667117/118251493-3d584f80-b4da-11eb-881d-d9261af5ac7f.png)

**Comment by nam-hle** [comment]
No clues. It works fine for me.

**Comment by vk-bytedance** [comment]
> No clues. It works fine for me.

Problem resolved! Thank you!

**Comment by vk-bytedance** [comment]
Bug fixed.
