### ISSUE TITLE
Is it possible to read data from a table?

### ISSUE THREAD

**Issue by Heinzen** [gajus/table#179]
I didn't locate anything in the current implementation dedicated to reading data from or manipulating existing data in a row. Are there any approaches?

**Comment by nam-hle** [comment]
Currently, we are supporting only convert data arrays into strings, not the opposite direction. Why do you need that? I assume that you had the data already?

**Comment by Heinzen** [comment]
I was looking into populating the table as a source of data. I will create a structure instead so I have an actual source and feed the table with that instead. Given the current structure of the project, do you think its feasible to make it a data source? Would be willing to contribute with a PR for that but I haven't investigated nearly enough to know whether that is even desirable.

**Comment by nam-hle** [comment]
Thanks for your spirit but IMO it is sadly not the main purpose of the package: _'Produces a string that represents array data in a text table.'_

**Comment by gajus** [comment]
Agreed. Out of scope for this package.
