### ISSUE TITLE
Potential regression in v3.8.0 - now builds es6 [compatibility with v0.12]

### ISSUE THREAD

**Issue by TimPerry** [gajus/table#18]
This commit seems to have made this project build out to es6: https://github.com/gajus/table/commit/8845d31e95bd6e810a780ffcba9b9e2cb1e03e3a

Is this expected? As I am now getting error such as this:

```
  let userConfig = arguments.length <= 1 || arguments[1] === undefined ? {} : 
  ^^^
SyntaxError: Unexpected strict mode reserved word
```

**Comment by TimPerry** [comment]
It is worth noting that in the project that threw this error I am using 0.12 of node

**Comment by gajus** [comment]
The reason it broke is because I am using `es2015-node4` preset, i.e. the minimum supported version is v4. For Node v0.12 support, please use any version LT v3.8.0.

**Comment by TimPerry** [comment]
I see, thank you for getting back to me so promptly. Unfortunately it's not our package that is directly using table, we are using stylelint, I will raise an issue with them.

**Comment by gajus** [comment]
@TimPerry Understood. CC me into the conversation.
