### ISSUE TITLE
Custom space character

### ISSUE THREAD

**Issue by niveKKumar** [gajus/table#183]
I use the table inside discord,only problem is that whitespace is trimmed so the output looks awful
![image](https://user-images.githubusercontent.com/48483421/134163330-c9d34d34-5342-471f-aa90-bb8d29823d9a.png)

Using it inside a codeblock (Which essentially doesnt trim whitspace) formats emojis wrong (which was also mentioned here in one of the issues)
![image](https://user-images.githubusercontent.com/48483421/134163443-b0b46488-b36b-483f-acda-bb113a6a477f.png)
The console log is flawless tho.

Maybe a custom "space" character could solve the problem ?

**Comment by gajus** [comment]
There is nothing we can do about Discord formatting. (There is no way to force monospace font.)

For code-block, this also seems Discord specific.

Not much we can do on our side, but if you come up with a solution, we can add it as a helper.
