### ISSUE TITLE
Module cannot be found error

### ISSUE THREAD

**Issue by tobias-93** [gajus/table#198]
When this module is used in context of another module (so simply by running `npm install -g <some-package>`), I get the following error:
```Error: Cannot find module '<...>\node_modules\table\dist\index.js'. Please verify that the package.json has a valid "main" entry```

I see that there is a file called index.js in the folder `dist\src`, so maybe some settings for package generation are wrong?
I expect commit d58adb17d4d976b4090c2c629d8b8d35334436ba broke it...

**Comment by nam-hle** [comment]
@tobias-93 My bad. I added `test` directory into `tsconfig` but did not re-check the bundle files.
Thanks for reporting.
