### ISSUE TITLE
Consider deprecating minWidth and maxWidth in favour of static width

### ISSUE THREAD

**Issue by gajus** [gajus/table#2]
The more I think of it, `minWidth` and `maxWidth` does not add value to the `table` package. CLI table output is meant to be predictable. Therefore, a static width definition makes a lot more sense.

**Comment by gajus** [comment]
https://github.com/gajus/table/commit/648cd43576fba6d20b62b838e318c2375be29ede

**Comment by zkochan** [comment]
I don't know why. This seemed like a really good feature

**Comment by chrishyle** [comment]
Just ran into this today for a use case with lots of variable-length data. `maxWidth` would have been helpful.

**Comment by nam-hle** [comment]
Hi @chrishyle, can this PR #177 help your use case?
