### ISSUE TITLE
[bug] package.json main points to wrong location

### ISSUE THREAD

**Issue by jurijzahn8019** [gajus/table#200]
Hi there, 

as you can see on screenshot:

![image](https://user-images.githubusercontent.com/44019949/144254008-a8128564-d8a7-41e6-9410-9d09009b8f16.png)

there are two folders inside dist.

so there is no `./dist/index.js`

maybe wrong typescript config?

**Comment by nam-hle** [comment]
HI @jurijzahn8019, the issue has been fixed in 6.7.5. Thanks.

**Comment by jurijzahn8019** [comment]
Cool Thanks!
