### ISSUE TITLE
Warning in DevTools about missing source maps

### ISSUE THREAD

**Issue by nolanlawson** [gajus/table#202]
Hello, thanks for making this library! It's incredibly useful. :slightly_smiling_face: 

I noticed when I run `node --inspect-brk` (i.e. the Node inspector tool) in a project containing `table`, the Chrome DevTools complain about not being able to load source maps:

![Screenshot from 2021-12-27 16-25-30](https://user-images.githubusercontent.com/283842/147515370-5f7a6b70-36b1-4e58-8486-c418c0709965.png)

The reason seems to be that the published `.js` files (e.g. [`alignTableData.js`](https://unpkg.com/browse/table@6.7.5/dist/src/alignTableData.js)) contain `//# sourceMappingURL=<filename>.js.map` at the end, but the `.js.map` files are not actually published.

It would be great if either 1) the `.js.map` files were published, or 2) the `sourceMappingURL` were removed, to avoid seeing a warning about missing source maps.

**Comment by ViieeS** [comment]
```
WARNING in ./node_modules/table/dist/src/wrapString.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/node_modules/table/src/wrapString.ts' file: Error: ENOENT: no such file or directory, open '/node_modules/table/src/wrapString.ts'

```

I see the same problem with React v18 (react-script v5)
