### ISSUE TITLE
Consider adding Javascript documentation

### ISSUE THREAD

**Issue by Nepoxx** [gajus/table#25]
Typescript is great, but not everyone is using it.

I struggled to find out how to use this module as `var table = require('table')` does not work (see https://github.com/gajus/table/issues/14 )

**Comment by gajus** [comment]
> Typescript is great, but not everyone is using it.

This package is using https://flowtype.org/. Regardless, it does not impact a consumer.

> I struggled to find out how to use this module as var table = require('table') does not work (see #14 )

It should be as simple as `var table = require('table')`. Lets continue conversation in the #14.
