### ISSUE TITLE
How do you create the table like in the demo

### ISSUE THREAD

**Issue by Nepoxx** [gajus/table#26]
I'm talking about this specific table: https://raw.githubusercontent.com/gajus/table/master/.README/demo.png

How do you create the header row that's bold?

**Comment by gajus** [comment]
See https://github.com/gajus/table/tree/master/test/README/usage

**Comment by ChrisTowles** [comment]
For those still wondering, use `chalk` to set the styling.

``` 
[
        chalk.bold('Spacecraft'),
        chalk.bold('Launch Date'),
        chalk.bold('Operator'),
        chalk.bold('Outcome'),
        chalk.bold('Remarks')
      ],

```
