### ISSUE TITLE
Move `ajv` and `ajv-keywords` to `devDependencies`.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [gajus/table#28]
They don't seem to be used anywhere except for tests.

**Comment by gajus** [comment]
That is not true.

See the `./dist`.

```bash
$ npm install table
test@1.0.0 /Users/gajuskuizinas/Documents/dev/gajus/test
└── table@4.0.1

npm WARN test@1.0.0 No description
npm WARN test@1.0.0 No repository field.
$ cd node_modules/table
$ ag ajv ./dist
dist/validateStreamConfig.js
2:var equal = require('ajv/lib/compile/equal');

dist/validateConfig.js
2:var equal = require('ajv/lib/compile/equal');
```

**Comment by wtgtybhertgeghgtwtg** [comment]
Sorry, I hadn't checked the build.

**Comment by jackwilsdon** [comment]
It looks like this can be re-visited, as [`ajv/lib/compile/equal.js`](https://github.com/epoberezkin/ajv/blob/9a13b2835f7ab5217c1cec3dd4f1de2a64ce8e7b/lib/compile/equal.js) seems to just pull in [`fast-deep-equal`](https://github.com/epoberezkin/fast-deep-equal), which is only 64K as opposed to `ajv`'s whopping 2.5MB.
