### ISSUE TITLE
Newline not allowed in column data

### ISSUE THREAD

**Issue by shellscape** [gajus/table#29]
Considering the following row array:

```js
let rows = [
  [chalk.blue('foobar'), 'The quick brown fox'],
  [chalk.blue('barbaz'), 'Jumps over\nthe lazy dog'],
  [chalk.blue('lorem'), 'ipsum']
];
```

Calling `table` results in the following error: `Error: Table data must not contain control characters.`

Checked the readme and there's nothing about this error. Does this module restrict newlines (and other control characters) in column values, or am I missing something and am a big dummy?

**Comment by gajus** [comment]
> Checked the readme and there's nothing about this error. Does this module restrict newlines (and other control characters) in column values, or am I missing something and am a big dummy?

It does.

See https://github.com/gajus/table/issues/9
