### ISSUE TITLE
Add ability to make cells span columns and/or rows.

### ISSUE THREAD

**Issue by gajus** [gajus/table#3]
This feature already exists in https://github.com/jamestalmage/cli-table2 package.

Visually, it looks pretty cool:

```
┌───────┬─────┬────┐
│ hello │ sup │ hi │
├───────┤     │    │
│ howdy │     │    │
├───┬───┼──┬──┤    │
│ o │ k │  │  │    │
└───┴───┴──┴──┴────┘
```

In `cli-table2` the syntax for that is:

```js
var table;

table = new Table({
    style: {
        head: [],
        border: []
    }
});

table.push(
    [
        {
            content: 'hello',
            colSpan: 2
        },
        {
            rowSpan: 2,
            colSpan: 2,
            content: 'sup'
        },
        {
            rowSpan: 3,
            content: 'hi'
        }
    ],
    [
        {
            content: 'howdy',
            colSpan:2
        }
    ],
    [
        'o',
        'k',
        '',
        ''
    ]
);
```

**Comment by gajus** [comment]
There is no practical need for this. CLI tables tend to be pretty simple. Projects that need this functionality should use @jamestalmage implementation.

**Comment by sarus** [comment]
I know you closed this but just wanted to say that one use case (that I think is practical) is for table headers.  For example, if you want the first row to span all columns and be a table description.

**Comment by gajus** [comment]
> I know you closed this but just wanted to say that one use case (that I think is practical) is for table headers. For example, if you want the first row to span all columns and be a table description.

The complexity that this feature adds to the codebase, relative to the demand, makes it not worth it.
