### ISSUE TITLE
How can I wrap text by \n ?

### ISSUE THREAD

**Issue by shuoshubao** [gajus/table#33]
# How can I wrap text As shown below    ###?
**There is not much content in each line.**
#
![image](https://cloud.githubusercontent.com/assets/8306792/23833423/27509956-0780-11e7-9c19-0d580f3ffc82.png)

> The following code will get a wrong result

```
stream.write([
  '🌹',
  ['Apple', 'Facebook', 'Homelink'].join('\n')
])
```

**Here is my config for table**
![image](https://cloud.githubusercontent.com/assets/8306792/23833512/e3021f8e-0781-11e7-88cc-a5e1ead6e11f.png)

**Comment by gajus** [comment]
https://github.com/gajus/table/issues/9
