### ISSUE TITLE
Why is ajv in dependencies, shouldn't it be in devDependencies?

### ISSUE THREAD

**Issue by mikelambert** [gajus/table#35]
I only see it used in the [test/ directories](https://github.com/gajus/table/search?utf8=%E2%9C%93&q=ajv&type=), so wouldn't it make more sense as a devDependency?

As it is, `eslint` imports `table`, and `table` pulls in `ajv`, and `ajv` has a [variety](https://github.com/epoberezkin/ajv/issues/373) [of](https://github.com/epoberezkin/ajv/issues/117) [issues](https://github.com/epoberezkin/ajv/issues/453) with webpack, that are supposedly [fixed in 5.0.0](https://github.com/epoberezkin/ajv/releases/tag/5.0.0). But this version is still pinned at 4.x in `table`, so I can't just upgrade it in my client...and seems like `table` could just do away with the dependency entirely!

**Comment by gajus** [comment]
It is being used, though the entry point is rather obfuscated.

See the "blame" of https://github.com/gajus/table/blob/4247a96fffe4f6a1dba2153471b1752f02e238ca/src/validateConfig.js#L1-L4 (Notice the `./dist` dependencies.).

**Comment by gajus** [comment]
The latest version is using ajv v5.

https://github.com/gajus/table/blob/4247a96fffe4f6a1dba2153471b1752f02e238ca/package.json#L8

**Comment by arcanis** [comment]
@gajus does something block the release? We're hitting this warning as well on Yarn :(

**Comment by gajus** [comment]
> @gajus does something block the release? We're hitting this warning as well on Yarn :(

Release of what? What warning?
