### ISSUE TITLE
Cannot set property '0' of undefined

### ISSUE THREAD

**Issue by WuQic** [gajus/table#46]
![image](https://user-images.githubusercontent.com/5144010/27956158-1b7ff140-634b-11e7-9001-f7e31292df34.png)

[ 'City' ] 0 0 'City'
[ '' ] 0 0 ''
```
node_modules/table/dist/mapDataUsingRowHeightIndex.js:53
        rowHeight[index2][index1] = part;
                                  ^

TypeError: Cannot set property '0' of undefined
```

**Comment by nam-hle** [comment]
This kind of bug is already fixed by pre-calculating the the maximum row height. So no way to access '0' from `undefined` theoretically. Please close this issue.
