### ISSUE TITLE
Provide a template using ASCII characters for terminals that do not support Unicode

### ISSUE THREAD

**Issue by gajus** [gajus/table#5]
This issue has been raised on https://github.com/Automattic/cli-table by @marcelklehr.

The proposal uses 3 ASCII characters to create table: `-`, `+`, `|`.

**Comment by gajus** [comment]
Version https://github.com/gajus/table/tree/2.1.0 adds new border style called "ramac".

```
# ramac (ASCII; for use in terminals that do not support Unicode characters)

+--+--+--+
|0A|0B|0C|
|--|--|--|
|1A|1B|1C|
|--|--|--|
|2A|2B|2C|
+--+--+--+
```

**Comment by marcelklehr** [comment]
Wow, nice. Thank you!
