### ISSUE TITLE
Error raised when on cell is empty

### ISSUE THREAD

**Issue by pavb74** [gajus/table#50]
Hi

The following error is raised by the method calculateCellHeight.js when one cell is empty:
   Unhandled rejection Error: Column width must be greater than 0.

I think it should raise such error only when a whole column is empty
The minWidth configuration option should also be used to compute this width 

Thanks

Pierre-André

**Comment by nam-hle** [comment]
This error has gone away.

```js
console.log(table([
  ['', ''],
  ['', ''],
]));
```

Output:
```
╔══╤══╗
║  │  ║
╟──┼──╢
║  │  ║
╚══╧══╝
```

Please consider to close this.
