### ISSUE TITLE
invisible output in console when using table with lodash 4.17.5

### ISSUE THREAD

**Issue by axten** [gajus/table#66]
We have a strange bug in [stylelint](https://github.com/stylelint/stylelint):

![bug](https://user-images.githubusercontent.com/1412778/39138545-7440a694-4720-11e8-892c-d4aa8e8ea685.png)

stylelint uses "table" for formatted output [(see Implementation)](https://github.com/stylelint/stylelint/blob/bd0f02a51d8ec566ab0bf6305772af83d28fcc42/lib/formatters/stringFormatter.js#L134)

as we found out, the reason is the new lodash release of version 4.17.5 [(see ticket)](https://github.com/wikimedia/grunt-stylelint/issues/49)

but from here we are without a clue and hope that you can help us finding out the root of the problem in lodash.

also, a quick fix could be to make a new release of table with a pinned lodash version to 4.17.4

thanks for help!

**Comment by axten** [comment]
I could bet this is the problems root:
https://github.com/gajus/table/blob/0dad920d257398f39079415ef47de283a21e6917/src/truncateTableData.js#L12

**Comment by gajus** [comment]
> I could bet this is the problems root:

Seems very likely.

**Comment by axten** [comment]
i found out that in our stack the lodash truncate function is overriden somewhere with the underscore.string truncate function... that really strange... sadly, I don't know how to fix this for now

**Comment by axten** [comment]
the bug is not in table, so im closing it
