### ISSUE TITLE
`Require` issues in previous versions of Node

### ISSUE THREAD

**Issue by tinwatchman** [gajus/table#7]
I'm running Node v0.12.0 (my company requires this whole security process in order to upgrade anything, it's a big hassle). When I try to import this library via the `require` function, like so:

```javascript
var table = require("table");
```

I get this result:
```
>> Error: Cannot find module './border/'
```

I would recommend either adding support for pre-ES6 versions of Node, or (more simply) add an [engines](https://docs.npmjs.com/files/package.json#engines) entry to your package.json file that sets the required version of Node higher than v0.12.0.

**Comment by gajus** [comment]
Nothing to do with ES6. The build was missing the `./border/` directory.

Fixed in https://github.com/gajus/table/tree/2.1.1.
