### ISSUE TITLE
First row top border never shows

### ISSUE THREAD

**Issue by zavan** [gajus/table#70]
Hi! First, thanks for the awesome project.

I'm using it to create tables for a Telegram bot, every response, no matter what table formatting I use, is not showing the top border.

![img_4377](https://user-images.githubusercontent.com/1722965/40736275-f6365774-6413-11e8-8736-9c1cbf3d1035.jpg)
![img_4378](https://user-images.githubusercontent.com/1722965/40736278-f6573c96-6413-11e8-83ad-22a44f621f89.PNG)

My code: https://github.com/zavan/monetus-fia-bot/blob/98352ec6991f19a601a95dd5608d46d39583e709/lib/messages/detailedPerformance.js

Version 4.0.3

**Comment by zavan** [comment]
Turns out it was a telegram issue. Fixed https://github.com/zavan/monetus-fia-bot/pull/10/files/98352ec6991f19a601a95dd5608d46d39583e709..dd95c73ab48ac6ccf985077d54cf13f8acea9a83

**Comment by benzino77** [comment]
@zavan how did you manage to display correct table in Telegram on mobile device?
On my web interface everything looks ok but on my device only "ascii" table works as expected.
Web interface:
![image](https://user-images.githubusercontent.com/15658235/66106386-fdbb4900-e5bd-11e9-97c4-986ab1258fba.png)
Mobile device:
![Screenshot_2019-10-03-08-41-21](https://user-images.githubusercontent.com/15658235/66106782-019b9b00-e5bf-11e9-9792-16fff33718ca.jpg)

**Comment by arshiaor** [comment]
> @zavan how did you manage to display correct table in Telegram on mobile device? On my web interface everything looks ok but on my device only "ascii" table works as expected. Web interface: ![image](https://user-images.githubusercontent.com/15658235/66106386-fdbb4900-e5bd-11e9-97c4-986ab1258fba.png) Mobile device: ![Screenshot_2019-10-03-08-41-21](https://user-images.githubusercontent.com/15658235/66106782-019b9b00-e5bf-11e9-9792-16fff33718ca.jpg)

exactly my question as well! when I send table as a markdown and/or html with <pre> tags in tg desktop everything is cool but in android or iphone the table gets messed up, idk why
