### ISSUE TITLE
header, where the header does not have columns

### ISSUE THREAD

**Issue by ORESoftware** [gajus/table#80]
Right now, basic output might look like:

```console
╔════╤════╤════╗
║ 0A │ 0B │ 0C ║
╟────┼────┼────╢
║ 1A │ 1B │ 1C ║
╟────┼────┼────╢
║ 2A │ 2B │ 2C ║
╚════╧════╧════╝
```

I am looking for something like this instead:

```console
╔══════════════╗
║no columns here
╟────┼────┼────╢
║ 1A │ 1B │ 1C ║
╟────┼────┼────╢
║ 2A │ 2B │ 2C ║
╚════╧════╧════╝
```

where the header does not have columns, is this possible?

**Comment by ORESoftware** [comment]
ughhh can't get the formatting right, but hopefully you get the idea

**Comment by gajus** [comment]
Would accept a PR that adds such functionality.

**Comment by nam-hle** [comment]
Maybe adding a property `title: string` to the table configuration is an acceptable solution, isn't it?

**Comment by nam-hle** [comment]
Here is my suggestion to support the header:
* API:
 	* Add the below typing to `TableUserConfig` with the name `header`.
	* Add `HeaderUserConfig` which is extended from `Omit<ColumnUserConfig, "width">` (the header width will be calculated from the table content in the runtime) with extra field `content`:
```typescript
export type HeaderConfig = Omit<ColumnUserConfig, 'width'> & {
  readonly content: string,
};
```

* Runtime:
	* The header alignment will be `center` by default if not be override.
	* Calculate the table content width `tableContentWidth` first, then use it to check `config.header.paddingLeft + config.header.paddingRight < tableContentWidth`

If acceptable, I'm willing to implement this 🚀
