### ISSUE TITLE
`@types/table` is on older version - write in TS maybe?

### ISSUE THREAD

**Issue by ORESoftware** [gajus/table#81]
Right now I have these installed:
 
```
"table": "^5.0.2"
"@types/table": "^4.0.5"
```

and I see this:

![screenshot from 2018-09-05 15-09-58](https://user-images.githubusercontent.com/11139560/45124053-c90c6200-b11d-11e8-954d-ad0c7ca9dcaa.png)

It really helps if libraries are written in TS...have external typings means the typings are never in sync, ultimately. Maybe I installed the wrong `@types` package?

**Comment by gajus** [comment]
"table" package does not support TS.

I am in process of adding Flowtype, though.

https://github.com/gajus/table/commit/946000f005f8e27b0a6af3c261d88c5f22e5b408
