### ISSUE TITLE
Cannot find module 'ajv/lib/compile/equal'

### ISSUE THREAD

**Issue by yutingzhao1991** [gajus/table#83]
ajv publish 6.6.0 equal removed: https://github.com/epoberezkin/ajv/commit/f9fcc504a4aaee3653af0f61c7681e2e80557f67

![image](https://user-images.githubusercontent.com/1061968/49208086-c4400d00-f3f1-11e8-817d-fb51bd02f59d.png)

**Comment by jaydenlin** [comment]
Got the same issue here

**Comment by csvan** [comment]
Temporary workaround for this is to add this to your `package.json`:

```
  "resolutions": {
    "ajv": "6.5.4"
  }
```

**Comment by whevether** [comment]
@yutingzhao1991 The file was removed. Manual replacement
http://www.pike.com/node_modules/localtunnel/node_modules/ajv/lib/compile/equal.js

**Comment by whevether** [comment]
@jaydenlin The file was removed. Manual replacement
http://www.pike.com/node_modules/localtunnel/node_modules/ajv/lib/compile/equal.js

**Comment by ybiquitous** [comment]
@gajus 
`ajv`'s author will [publish the new version](https://github.com/epoberezkin/ajv/issues/889#issuecomment-442783090) of `ajv` in a few hours, so then, could you please publish new build version of `table`? 🙇 🙇 🙇
