### ISSUE TITLE
cell space will too long when in cmd

### ISSUE THREAD

**Issue by Yohox** [gajus/table#91]
![_20190213155431](https://user-images.githubusercontent.com/23305206/52695540-cacd3200-2fa7-11e9-967c-f9d2966d157d.png)

**Comment by Yohox** [comment]
this is code 
`
export function createTable(data) {
  return table(data);
}
`

**Comment by gajus** [comment]
What version?

**Comment by Yohox** [comment]
@gajus  it's 5.2.3

**Comment by gajus** [comment]
Can you share the `data` as a JSON?

**Comment by Yohox** [comment]
@gajus  Hello this is  data JSON thanks ~

`
[["Ext","Requests","Time","Time/Request","Description"],["js",1261,"6s","4ms","JavaScript files"],["Total",1261,"6s","",""]]
`

**Comment by gajus** [comment]
<img width="552" alt="screenshot 2019-02-14 at 08 25 52" src="https://user-images.githubusercontent.com/973543/52773138-293ef280-3032-11e9-8704-c7e5b0e5681e.png">

Cannot replicate the issue.
