### ISSUE TITLE
Latest version should be a major change to v6.x

### ISSUE THREAD

**Issue by molinto** [gajus/table#97]
The version of node has changed in your latest build as you are now using eslint 6.0.1 which requires node v8. This is going to affect a lot of people who use eslint. Change to a major release please as its a breaking change, taken me 2 hours to find this info out.

I have to use v6.9.5 for a physical box.
My code is running eslint ^5.16.0, which uses your "table": "^5.2.3".

This no longer builds as latest version of table requires eslint": "^6.0.1" - which in turn needs Node version 8. even though your engine is "node": ">=6.0.0".

I have to remove eslint altogether to fix.

**Comment by gajus** [comment]
https://github.com/gajus/table/commit/539f4e09958ddf6e919ba5367d0840fa2dbb967d

**Comment by molinto** [comment]
Thank you

**Comment by molinto** [comment]
@gajus Will this be pushed to NPM soon?
https://www.npmjs.com/package/table

**Comment by molinto** [comment]
You have updated "string-width" from "^3.0.0" to "^4.1.0" dude.
This also required node v8+
https://github.com/sindresorhus/string-width/blob/master/package.json#L13
